// <auto-generated />
using System;
using IdentityFromScratch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityFromScratch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityFromScratch.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VAT")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Map reading and navigation course",
                            Name = "The Competent Navigator",
                            NetPrice = 499.99m,
                            TotalPrice = 599.99m,
                            VAT = 100m
                        });
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Enrolment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("MemberId1")
                        .HasColumnType("text");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentProvider")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentProviderPayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentProviderPaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("VATAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId1");

                    b.ToTable("Enrolments");
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Lessons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "In this lesson we explore the idea of a map as a bird's eye of the ground. Topographical maps represent physical, man-made and relief features and are used for a variety or purposes including land navigation i.e. moving safely and efficiently from one location to another, which is exactly what we will be using them for in this course.",
                            Header = "A map is simply a bird's eye view of the ground.",
                            Name = "Lesson 1 - What is a map?"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "In this lesson we explore the pros and cons of each and recommend which type of map you should use and when.",
                            Header = "here are paper, laminated, fabric and digital maps.",
                            Name = "Lesson 2 - What types of maps are there?"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Description = "In this lesson we explore maps of different scales to see how much detailed information they contain.",
                            Header = "Scale is simply how much smaller the map is compared to the ground the map represents.",
                            Name = "Lesson 3 - What is scale?"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Description = "In this lesson we explore what map scales are useful for which purposes and activities so that you can select the appropriate scales of maps to plan and execute your outdoor activities.",
                            Header = "Different map scales suit different purposes and activities.",
                            Name = "Lesson 4 - What map scales suit which purposes?"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Description = "In this lesson we explore the margins of a variety of maps to discover the important information that you will need to know when using them for navigation.",
                            Header = "Most maps contain important information in the margins of the map.",
                            Name = "Lesson 5 - What important information is there in the margins of a map?"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 1,
                            Description = "In this lesson we explore grid references and geographical coordinates and how to use them to pin point any location on the map and on the ground.",
                            Header = "To pin point your location on a map and on the ground you will need a unique grid reference or set of geographical coordinates.",
                            Name = "Lesson 6 - What are grid references and geographical coordinates?"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 1,
                            Description = "In this lesson we explore how direction is measured as an angle from North together with the tools we use to measure it, protractors and compasses.",
                            Header = "Direction is measured as an angle from North.",
                            Name = "Lesson 7 - What is direction?"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 1,
                            Description = "In this lesson we explore the Grid Magnetic Angle (GMA), the angular difference between the grid north on your map and the magnetic north measured by your compass. We examine how to make adjustments to bearings to avoid errors as you move them from map to compass and compass to map.",
                            Header = "Grid Magnetic Angle (GMA) is the angular difference between grid north and magnetic north.",
                            Name = "Lesson 8 - What is the Grid Magnetic Angle (GMA)?"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            Description = "In this lesson we explore how contour lines are used to represent elevation and relief. We explore how this provides information on the height and shape of features on the ground and why this is a navigation superpower.",
                            Header = "Contour lines are lines on the map that delineate points of equal height or elevation.",
                            Name = "Lesson 9 - What are contour lines?"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 1,
                            Description = "In this lesson we explore how to line up or orientate your map with features on the ground and/or with your compass. In this way what you see in front of you is lined up with what you see on your map which is essential and vital for accurate navigation.",
                            Header = "An important first step in navigating any leg of your route is to orientate your map to the ground.",
                            Name = "Lesson 10 - How to orientate a map"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 1,
                            Description = "In this lesson we explore how to use a ruler or the side of your compass to measure distance between two points in mm or cm on the map and convert it to distance on the ground in m or km by using the map's scale.",
                            Header = "Distance on a map is measured in mm or cm and then converted to m and km on the ground based on the scale of the map.",
                            Name = "Lesson 11 - How to measure distance on a map"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 1,
                            Description = "In this lesson we explore how to take a grid bearing and convert it to a magnetic bearing which you will need to follow if you can't see your destination because physical features obscure it, or because of poor visibility at night or in bad weather.",
                            Header = "How to take a grid bearing from the map and convert it to a magnetic bearing on the ground.",
                            Name = "Lesson 12 - How to take a grid bearing from your map"
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 1,
                            Description = "In this lesson we explore how to walk along and follow a magnetic compass bearing to reach your destination point or target at night or in poor visibility. You may recall we converted this magnetic bearing from a grid bearing we took from the map in the last lesson.",
                            Header = "If you can't see your destination you will need to follow a compass bearing to get there.",
                            Name = "Lesson 13 - How to follow a compass bearing"
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 1,
                            Description = "In this lesson we explore how to use a compass to take a magnetic bearing to a feature you can see on the ground.",
                            Header = "Using your compass to take a magnetic bearing to a feature you can see on the ground.",
                            Name = "Lesson 14 - How to take a magnetic bearing"
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 1,
                            Description = "In this lesson we explore how to convert magnetic bearings into back bearings in preparation for a resection to fix your position.",
                            Header = "Back bearings are 180 degree reversed magnetic bearings important for resections to fix your position.",
                            Name = "Lesson 15 - How to convert magnetic bearings into back bearings"
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 1,
                            Description = "In this lesson we explore how to use two or three bearings to fix any position and two to three back bearings to fix your current position on the map and on the ground.",
                            Header = "How to use bearings to fix any position and back bearings to fix your current position both on the map and on the ground",
                            Name = "Lesson 16 - How to do an intersection to fix any position and a resection to fix your current position."
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 1,
                            Description = "In this lesson we explore the idea of map memory and using your thumb to mark where you are on the map, and thus the ground, at all times, mentally ticking off prominent collecting features as you go and identify a catching feature to make sure you don’t overshoot and miss your destination point for the current leg of your route.",
                            Header = "Thumbing the map means keeping your thumb continuously on your current location and mentally ticking off prominent man-made and physical collecting features as you go.",
                            Name = "Lesson 17 - How to use collecting features and map memory to thumb a map"
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 1,
                            Description = "In this lesson we explore how you can navigate by walking along linear man-made and physical features on the ground using them literally like a handrail to guide you on route to you next destination.",
                            Header = "Linear man-made features such as walls, roads and paths or physical features such as rivers and valleys, ridges and coastlines can be used as handrails to navigate by on route to you next destination point.",
                            Name = "Lesson 18 - How to use linear man-made and physical features as handrails to guide you on route"
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 1,
                            Description = "In this lesson we cover your speed over the ground, how you can estimate distance covered and the duration or time to your next target or destination point.",
                            Header = "How far, how fast and what time to your next destination point?",
                            Name = "Lesson 19 - How to calculate time, speed and distance on route"
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 1,
                            Description = "In this lesson we explore the importance of keeping your route sections, or legs, short to avoid compass errors.",
                            Header = "Over short distances, compass errors are small and easily spotted.",
                            Name = "Lesson 20 - How to avoid compass errors by keeping legs short"
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 1,
                            Description = "In this lesson we explore how to plan out the entire route in advance with a route card and the importance of sharing this with a responsible adult in case of emergencies.",
                            Header = "Plan ahead with a route card and share this with others for safety in case of emergencies.",
                            Name = "Lesson 21 - How to produce a route card to plan ahead"
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 1,
                            Description = "In this lesson we explore how to produce the same route card using digital maps.",
                            Header = "It is easier to plan a route with digital maps.",
                            Name = "Lesson 22 - Using digital maps to plan a route"
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 1,
                            Description = "In this lesson we pull everything together with the 10 Qs and the 5 Ds of practical navigation.",
                            Header = "Putting the theory to practice.",
                            Name = "Lesson 23 - How to do practical navigation"
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 1,
                            Description = "In this lesson we give a brief introduction to navigating with digital maps and a GPS.",
                            Header = "Using Digital Maps and GPS.",
                            Name = "Lesson 24 - How to navigate with digital maps and a GPS"
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 1,
                            Description = "In this lesson we explore how to use digital maps and a GPS as a secondary backup to confirm the accuracy of your manual map reading, compass work and navigation.",
                            Header = "Don't rely on GPS Alone.",
                            Name = "Lesson 25 - How to practice hybrid map reading and navigation"
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 1,
                            Description = "In this bonus lesson we explore what options are open to you to further develop your map reading, compass and navigation skills.",
                            Header = "What next?",
                            Name = "Bonus Lesson - Next Steps"
                        });
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("EnrolmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OTPExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Objectives", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Objectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LessonId = 1,
                            Name = "Objective 1.1",
                            Objective = "By the end of this lesson you will understand and be able to describe precisely what maps are and what they are used for."
                        },
                        new
                        {
                            Id = 2,
                            LessonId = 1,
                            Name = "Objective 1.2",
                            Objective = "By the end of this lesson you will understand that maps use graphics and symbols to represent information about physical, man-made and relief features and their relative position and relationship to one another such that they can be used for safely and efficiently navigating over the land."
                        },
                        new
                        {
                            Id = 3,
                            LessonId = 2,
                            Name = "Objective 2.1",
                            Objective = "By the end of this lesson you will be able to articulate the advantages and disadvantages of each type of map."
                        },
                        new
                        {
                            Id = 4,
                            LessonId = 2,
                            Name = "Objective 2.2",
                            Objective = "By the end of this lesson you will be able to select maps suitable for your outdoor activities."
                        },
                        new
                        {
                            Id = 5,
                            LessonId = 3,
                            Name = "Objective 3.1",
                            Objective = "By the end of this lesson you will understand and be able to explain what map scales are."
                        },
                        new
                        {
                            Id = 6,
                            LessonId = 3,
                            Name = "Objective 3.2",
                            Objective = "By the end of this lesson you will be able to explain what 1:25,000, 1:50,000 and 1:250,000 map scales are."
                        },
                        new
                        {
                            Id = 7,
                            LessonId = 4,
                            Name = "Objective 4.1",
                            Objective = "By the end of this lesson you will know what scale of maps are good for planning and which for are good to take into the outdoors for specific pursuits and activities; walking, hiking, running, cycling and canoeing or even sailing."
                        },
                        new
                        {
                            Id = 8,
                            LessonId = 4,
                            Name = "Objective 4.2",
                            Objective = "By the end of this lesson you will be able to select suitable scales of maps appropriate for your outdoor activities."
                        },
                        new
                        {
                            Id = 9,
                            LessonId = 5,
                            Name = "Objective 5.1",
                            Objective = "By the end of this lesson you will understand and be able to use the information in the margins of the map to help you read and interpret the map for navigation purposes."
                        },
                        new
                        {
                            Id = 10,
                            LessonId = 5,
                            Name = "Objective 5.2",
                            Objective = "By the end of this lesson you will understand and be able find other sources of information to help with navigation in your local area."
                        },
                        new
                        {
                            Id = 11,
                            LessonId = 6,
                            Name = "Objective 6.1",
                            Objective = "By the end of this lesson you will understand and be able to explain what four, six and eight figure grid references are."
                        },
                        new
                        {
                            Id = 12,
                            LessonId = 6,
                            Name = "Objective 6.2",
                            Objective = "the end of this lesson you will understand and be able to explain what latitude and longitude coordinates are."
                        },
                        new
                        {
                            Id = 13,
                            LessonId = 6,
                            Name = "Objective 6.3",
                            Objective = "By the end of this lesson you will be able use a romer or ruler to measure four, six and eight figure grid references to give your current location or another location on 1:25,000 and 1:50,000 scale maps."
                        },
                        new
                        {
                            Id = 14,
                            LessonId = 7,
                            Name = "Objective 7.1",
                            Objective = "By the end of this lesson you will understand be able to explain how direction is measured as bearings from North and appreciate the difference between the three Norths, Grid North, True North and Magnetic North."
                        },
                        new
                        {
                            Id = 15,
                            LessonId = 7,
                            Name = "Objective 7.2",
                            Objective = "By the end of this lesson you will understand and describe various direction measuring tools such as baseplate compasses, prismatic and lensatic sighting compasses, rulers and protractors."
                        },
                        new
                        {
                            Id = 16,
                            LessonId = 8,
                            Name = "Objective 8.1",
                            Objective = "By the end of this lesson you will know how to work out the GMA for your local area."
                        },
                        new
                        {
                            Id = 17,
                            LessonId = 8,
                            Name = "Objective 8.2",
                            Objective = "By the end of this lesson you will convert magnetic bearings into grid bearings and grid bearings into magnetic bearings by adding or subtracting the GMA for your local area."
                        },
                        new
                        {
                            Id = 18,
                            LessonId = 9,
                            Name = "Objective 9.1",
                            Objective = "By the end of this lesson you will understand and be able to explain how contour lines join up points of equal height on the land."
                        },
                        new
                        {
                            Id = 19,
                            LessonId = 9,
                            Name = "Objective 9.2",
                            Objective = "By the end of this lesson you will be able to interpret the three A's of contour lines and relief; Aspect (the direction of a slope), Altitude (height of the land) and Angle (the steepness of a slope). All this information helps you to visualise the shape of the land before you get there, and how easy or difficulty it is to traverse and how long it may take to get to you next destination point."
                        },
                        new
                        {
                            Id = 20,
                            LessonId = 9,
                            Name = "Objective 9.3",
                            Objective = "By the end of this lesson you will be able to recognise and navigate by natural features in the landscape such as spot heights, cols, ridges, rivers and valleys, spurs and reentrants, all very useful features we can use to safely and efficiently navigate over the land."
                        },
                        new
                        {
                            Id = 21,
                            LessonId = 10,
                            Name = "Objective 10.1",
                            Objective = "By the end of this lesson you will be able to orient your map using man-made and physical features on the ground."
                        },
                        new
                        {
                            Id = 22,
                            LessonId = 10,
                            Name = "Objective 10.2",
                            Objective = "By the end of this lesson you will be able to orient your map using your compass."
                        },
                        new
                        {
                            Id = 23,
                            LessonId = 11,
                            Name = "Objective 11.1",
                            Objective = "By the end of this lesson you will be able to measure distance on a 1:25,000 map and convert it accurately to distance on the ground."
                        },
                        new
                        {
                            Id = 24,
                            LessonId = 11,
                            Name = "Objective 11.2",
                            Objective = "By the end of this lesson you will be able to measure distance on a 1:50,000 map and convert it accurately to distance on the ground."
                        },
                        new
                        {
                            Id = 25,
                            LessonId = 12,
                            Name = "Objective 12.1",
                            Objective = "By the end of this lesson you will be able to take a grid bearing from your current location to your next destination point"
                        },
                        new
                        {
                            Id = 26,
                            LessonId = 12,
                            Name = "Objective 12.2",
                            Objective = "By the end of this lesson you will be able to convert a grid bearing to a magnetic bearing using the current Grid Magnetic Angle (GMA) for your area."
                        },
                        new
                        {
                            Id = 27,
                            LessonId = 13,
                            Name = "Objective 13.1",
                            Objective = "By the end of this lesson you will be able to identify prominent features on your magnetic compass bearing that you can walk towards as reference points and thus stay on track to reach your destination."
                        },
                        new
                        {
                            Id = 28,
                            LessonId = 13,
                            Name = "Objective 13.2",
                            Objective = "By the end of this lesson you will be able to walk along your compass bearing by taking back bearings to last known positions behind you thus checking you are still on track to reach your destination."
                        },
                        new
                        {
                            Id = 29,
                            LessonId = 13,
                            Name = "Objective 13.3",
                            Objective = "By the end of this lesson you will be able to walk along your compass bearing by positioning a member of your group ahead of you on that bearing and then leap frogging them using back bearings and so on until you reach your destination."
                        },
                        new
                        {
                            Id = 30,
                            LessonId = 14,
                            Name = "Objective 14.1",
                            Objective = "By the end of this lesson you will be able to select an appropriate sighting compass to take a magnetic bearing.\n\n"
                        },
                        new
                        {
                            Id = 31,
                            LessonId = 14,
                            Name = "Objective 14.2",
                            Objective = "By the end of this lesson you will be able to line up your compass sight with a feature on the ground and read off the magnetic bearing from your current location to the feature you can see on the ground."
                        },
                        new
                        {
                            Id = 32,
                            LessonId = 15,
                            Name = "Objective 15.1",
                            Objective = "By the end of this lesson you will be able to convert a magnetic bearing into a back bearing (i.e. the bearing from that feature to your location) by adding 180 degrees where the bearing is less than 180 degree.\n\n"
                        },
                        new
                        {
                            Id = 33,
                            LessonId = 15,
                            Name = "Objective 15.2",
                            Objective = "By the end of this lesson you will be able to convert a magnetic bearing into a back bearing (i.e. the bearing from that feature to your location) by subtracting 180 degrees where the bearing is more than 180 degree."
                        },
                        new
                        {
                            Id = 34,
                            LessonId = 16,
                            Name = "Objective 16.1",
                            Objective = "By the end of this lesson you will be able to take a magnetic bearing from your current known position to a feature on the ground whose position you want to fix."
                        },
                        new
                        {
                            Id = 35,
                            LessonId = 16,
                            Name = "Objective 16.2",
                            Objective = "By the end of this lesson you will be able to move to another known position to take another magnetic bearing to the same feature on the ground whose position you wish to fix, and repeat for a third if necessary."
                        },
                        new
                        {
                            Id = 36,
                            LessonId = 16,
                            Name = "Objective 16.3",
                            Objective = "By the end of this lesson you will be able to convert these magnetic bearings into grid bearings using the current Grid Magnetic Angle for your area."
                        },
                        new
                        {
                            Id = 37,
                            LessonId = 16,
                            Name = "Objective 16.4",
                            Objective = "By the end of this lesson you will be able to plot each of these grid bearings on the map from their known positions revealing the position of the feature on the map where they intersect."
                        },
                        new
                        {
                            Id = 38,
                            LessonId = 16,
                            Name = "Objective 16.5",
                            Objective = "By the end of this lesson you will be able to take two to three magnetic bearings to prominent features you can see both on the ground and on your map."
                        },
                        new
                        {
                            Id = 39,
                            LessonId = 16,
                            Name = "Objective 16.6",
                            Objective = "By the end of this lesson you will be able to convert the two to three magnetic bearings into back bearings, i.e. the bearings from the two to three prominent features to your location."
                        },
                        new
                        {
                            Id = 40,
                            LessonId = 16,
                            Name = "Objective 16.7",
                            Objective = "By the end of this lesson you will be able to convert the two to three back bearings into grid bearings by adjusting for the current Grid Magnetic Angle (GMA) in your area."
                        },
                        new
                        {
                            Id = 41,
                            LessonId = 16,
                            Name = "Objective 16.8",
                            Objective = "By the end of this lesson you will be able to plot the two to three grid bearings from the two to three prominent features on the map to reveal your location where the lines intersect and thus fix your position."
                        },
                        new
                        {
                            Id = 42,
                            LessonId = 17,
                            Name = "Objective 17.1",
                            Objective = "By the end of this lesson you will be able to identify and memorise a series of prominent collecting features on your route from the map."
                        },
                        new
                        {
                            Id = 43,
                            LessonId = 17,
                            Name = "Objective 17.2",
                            Objective = "By the end of this lesson you will be able to recognise and tick off each collecting feature as you navigate your route and move your thumb to mark where you are on the map as you go."
                        },
                        new
                        {
                            Id = 44,
                            LessonId = 17,
                            Name = "Objective 17.3",
                            Objective = "By the end of this lesson, if you have missed your destination point, you will recognise your catching feature, realise you have missed your destination point, and retrace your steps to find it."
                        },
                        new
                        {
                            Id = 45,
                            LessonId = 18,
                            Name = "Objective 18.1",
                            Objective = "By the end of this lesson you will be able to identify linear man-made and physical features on the map together with collecting features and catch points on route to your destination."
                        },
                        new
                        {
                            Id = 46,
                            LessonId = 18,
                            Name = "Objective 18.2",
                            Objective = "By the end of this lesson you will be able to follow linear man-made and physical features on the ground together with collecting features and catch points on route to your destination."
                        },
                        new
                        {
                            Id = 47,
                            LessonId = 19,
                            Name = "Objective 19.1",
                            Objective = "By the end of this lesson you will know how many steps or paces you walk over a 100m distance and at what speed."
                        },
                        new
                        {
                            Id = 48,
                            LessonId = 19,
                            Name = "Objective 19.2",
                            Objective = "By the end of this lesson you will know the number of minutes to add per 10m of elevation gained or 30m of elevation lost."
                        },
                        new
                        {
                            Id = 49,
                            LessonId = 19,
                            Name = "Objective 19.3",
                            Objective = "By the end of this lesson you will be able to estimate how long it will take to walk to your next destination, taking into consideration the distance, your speed and the elevation gained or lost on route."
                        },
                        new
                        {
                            Id = 50,
                            LessonId = 19,
                            Name = "Objective 19.4",
                            Objective = "By the end of this lesson you will be able to estimate distance walked by pacing and keeping track of each 100m section of ground covered based on your personal and known measure of the number of steps you walk over a 100m distance."
                        },
                        new
                        {
                            Id = 51,
                            LessonId = 20,
                            Name = "Objective 20.1",
                            Objective = "By the end of this lesson you will be able to calculate the effect of compass errors over various distances."
                        },
                        new
                        {
                            Id = 52,
                            LessonId = 20,
                            Name = "Objective 20.2",
                            Objective = "By the end of this lesson you will be able to assess the risk of errors over short distances and whether to accept or mitigate such errors."
                        },
                        new
                        {
                            Id = 53,
                            LessonId = 21,
                            Name = "Objective 21.1",
                            Objective = "By the end of this lesson you will be able to plan out and draw up a route card with waypoints/destination points, bearings, distances, elevation gained and lost and timings for each leg."
                        },
                        new
                        {
                            Id = 54,
                            LessonId = 21,
                            Name = "Objective 21.2",
                            Objective = "By the end of this lesson you will understand the importance of sharing your route card with a responsible adult in case of emergencies."
                        },
                        new
                        {
                            Id = 55,
                            LessonId = 21,
                            Name = "Objective 21.3",
                            Objective = "By the end of this lesson you will understand the importance of sticking to your planned route so, in case emergencies, the alarm can be raised and emergency services have a fighting chance of finding you."
                        },
                        new
                        {
                            Id = 56,
                            LessonId = 22,
                            Name = "Objective 22.1",
                            Objective = "By the end of this lesson you will be able to set waypoints and plan a route with distances and bearings, elevation gained and lost together with timings.\n\n"
                        },
                        new
                        {
                            Id = 57,
                            LessonId = 22,
                            Name = "Objective 22.2",
                            Objective = "By the end of this lesson you will be able to export your route plan as a GPX file and import this file into other GPS devices."
                        },
                        new
                        {
                            Id = 58,
                            LessonId = 22,
                            Name = "Objective 22.3",
                            Objective = "By the end of this lesson you will be able print off route card to share with others in case of emergencies."
                        },
                        new
                        {
                            Id = 59,
                            LessonId = 23,
                            Name = "Objective 23.1",
                            Objective = "By the end of this lesson you will know the 10 Qs or questions you need to ask as you move from one location, your start point to another location, your destination point, for each leg of your route."
                        },
                        new
                        {
                            Id = 60,
                            LessonId = 23,
                            Name = "Objective 23.2",
                            Objective = "By the end of this lesson you will know the 5 Ds of navigation, Destination, Distance, Duration, Direction and Description and how to apply them to navigate safely and efficiently."
                        },
                        new
                        {
                            Id = 61,
                            LessonId = 23,
                            Name = "Objective 23.3",
                            Objective = "By the end of this lesson you will be able to pull together into a coherent whole all the skills learned so far and apply them effectively to navigate safely and efficiently in lowland landscapes in good visibility."
                        },
                        new
                        {
                            Id = 62,
                            LessonId = 24,
                            Name = "Objective 24.1",
                            Objective = "By the end of this lesson you will be able to select an appropriate digital map and GPS device."
                        },
                        new
                        {
                            Id = 63,
                            LessonId = 24,
                            Name = "Objective 24.2",
                            Objective = "By the end of this lesson you will be able to use a digital map and navigate by GPS."
                        },
                        new
                        {
                            Id = 64,
                            LessonId = 25,
                            Name = "Objective 25.1",
                            Objective = "By the end of this lesson you will be able to navigate first and foremost using a paper, laminated or fabric map and compass."
                        },
                        new
                        {
                            Id = 65,
                            LessonId = 25,
                            Name = "Objective 25.2",
                            Objective = "By the end of this lesson you will be able to check your manual map reading and navigation efforts using your GPS thus setting up a positive reinforcement loop to further develop your skills as a competent navigator."
                        },
                        new
                        {
                            Id = 66,
                            LessonId = 26,
                            Name = "Objective",
                            Objective = "By the end of this lesson you will know where to go and how to further develop your newly acquired manual map reading, compass and navigation skills to navigate in more challenging environments such as upland areas and in reduced visibility conditions."
                        });
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNext")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("MemberId1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("MemberId1");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Enrolment", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Course", "Course")
                        .WithMany("Enrolements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityFromScratch.Models.Member", "Member")
                        .WithMany("Enrolements")
                        .HasForeignKey("MemberId1");

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Lessons", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Objectives", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Progress", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Lessons", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityFromScratch.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityFromScratch.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IdentityFromScratch.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Course", b =>
                {
                    b.Navigation("Enrolements");
                });

            modelBuilder.Entity("IdentityFromScratch.Models.Member", b =>
                {
                    b.Navigation("Enrolements");
                });
#pragma warning restore 612, 618
        }
    }
}
